apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  type: oci
  interval: 1h
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  timeout: 10m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.21.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    serviceAccount:
      name: cert-manager
      annotations:
        iam.gke.io/gcp-service-account: grafana-assessment@ornate-artifact-414911.iam.gserviceaccount.com
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
    webhook:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          memory: 128Mi
    cainjector:
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 256Mi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acme-email
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: acme-email
    creationPolicy: Owner
    template:
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        ACME_EMAIL: "{{ .email | trim }}"
  data:
    - secretKey: email
      remoteRef:
        key: email-account
        version: latest
