apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.21.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    crds:
      enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: ${GCP_SERVICE_ACCOUNT}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acme-email
  namespace: flux-system
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        ACME_EMAIL: '{{ .email | trim }}'
  data:
  - secretKey: email
    remoteRef:
      key: email-account
