apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acme-email
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: acme-email
    creationPolicy: Owner
    template:
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        ACME_EMAIL: "{{ .email | trim }}"
  data:
    - secretKey: email
      remoteRef:
        key: email-account
        version: latest
