apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: 2.9.6
    registry: ghcr.io/fluxcd
  sync:
    kind: GitRepository
    url: https://github.com/michaelalinks/grafana-assessment.git
    ref: refs/heads/main
    path: flux
