apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/envoy-gateway
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      GCP_SERVICE_ACCOUNT: "${GCP_SERVICE_ACCOUNT}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/external-dns
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: envoy-gateway
  postBuild:
    substitute:
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
      GCP_SERVICE_ACCOUNT: "${GCP_SERVICE_ACCOUNT}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-config
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/envoy-gateway/config
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: envoy-gateway
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      current: has(status.conditions) && status.conditions.exists(c, c.type == 'Programmed' && c.status == 'True' && c.observedGeneration == metadata.generation)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-store
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/external-secrets/config
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets
  postBuild:
    substitute:
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: secret-store
  postBuild:
    substitute:
      GCP_SERVICE_ACCOUNT: "${GCP_SERVICE_ACCOUNT}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuers
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/cert-manager/config
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  postBuild:
    substitute:
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
    substituteFrom:
      - kind: Secret
        name: acme-email
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-issuers
    - name: gateway-config
    - name: prometheus
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: ListenerSet
      current: has(status.conditions) && status.conditions.exists(c, c.type == 'Programmed' && c.status == 'True' && c.observedGeneration == metadata.generation)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  prune: true
  wait: true
  path: ./flux/installs/prometheus
  sourceRef:
    kind: GitRepository
    name: flux-system
