apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.9.6"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    networkPolicy: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: https://github.com/michaelalinks/iso-grafana-install.git
    ref: refs/heads/feat/flux-bootstrap
    path: clusters/gke
