apiVersion: 1
prune: true
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
