apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policy.yaml
  - networking.yaml
  - grafana.yaml
configMapGenerator:
  - name: grafana-config
    namespace: grafana
    files:
      - config/grafana.ini
      - config/datasources.yaml
      - config/dashboards.yaml
  - name: grafana-dashboard
    namespace: grafana
    files:
      - config/overview.json
