apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    healthtech.michaelalinks.com/gateway: public
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: grafana
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.healthtech.michaelalinks.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-gcp
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: grafana
  namespace: grafana
spec:
  parentRef:
    name: public
    namespace: envoy-gateway-system
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
    - name: https
      hostname: grafana.healthtech.michaelalinks.com
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: grafana-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  namespace: grafana
spec:
  hostnames:
    - grafana.healthtech.michaelalinks.com
  parentRefs:
    - name: public
      namespace: envoy-gateway-system
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: grafana
spec:
  hostnames:
    - grafana.healthtech.michaelalinks.com
  parentRefs:
    - name: grafana
      kind: ListenerSet
      group: gateway.networking.k8s.io
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          port: 3000
